/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bor_vulkan_structs_VkPhysicalDeviceLimits */

#ifndef _Included_bor_vulkan_structs_VkPhysicalDeviceLimits
#define _Included_bor_vulkan_structs_VkPhysicalDeviceLimits
#ifdef __cplusplus
extern "C" {
#endif
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKAPPLICATIONINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKAPPLICATIONINFO_ID 1L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKINSTANCECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKINSTANCECREATEINFO_ID 2L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKALLOCATIONCALLBACKS_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKALLOCATIONCALLBACKS_ID 3L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICEFEATURES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICEFEATURES_ID 4L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKFORMATPROPERTIES_ID 5L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKEXTENT3D_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKEXTENT3D_ID 6L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEFORMATPROPERTIES_ID 7L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICELIMITS_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICELIMITS_ID 8L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICESPARSEPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICESPARSEPROPERTIES_ID 9L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICEPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICEPROPERTIES_ID 10L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKQUEUEFAMILYPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKQUEUEFAMILYPROPERTIES_ID 11L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYTYPE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYTYPE_ID 12L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYHEAP_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYHEAP_ID 13L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICEMEMORYPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPHYSICALDEVICEMEMORYPROPERTIES_ID 14L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDEVICEQUEUECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDEVICEQUEUECREATEINFO_ID 15L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDEVICECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDEVICECREATEINFO_ID 16L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKEXTENSIONPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKEXTENSIONPROPERTIES_ID 17L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKLAYERPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKLAYERPROPERTIES_ID 18L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBMITINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBMITINFO_ID 19L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYALLOCATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYALLOCATEINFO_ID 20L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKMAPPEDMEMORYRANGE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKMAPPEDMEMORYRANGE_ID 21L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYREQUIREMENTS_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYREQUIREMENTS_ID 22L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEFORMATPROPERTIES_ID 23L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEMEMORYREQUIREMENTS_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEMEMORYREQUIREMENTS_ID 24L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEMEMORYBIND_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEMEMORYBIND_ID 25L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEBUFFERMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEBUFFERMEMORYBINDINFO_ID 26L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEOPAQUEMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEOPAQUEMEMORYBINDINFO_ID 27L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGESUBRESOURCE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGESUBRESOURCE_ID 28L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKOFFSET3D_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKOFFSET3D_ID 29L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEMEMORYBIND_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEMEMORYBIND_ID 30L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPARSEIMAGEMEMORYBINDINFO_ID 31L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKBINDSPARSEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKBINDSPARSEINFO_ID 32L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKFENCECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKFENCECREATEINFO_ID 33L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSEMAPHORECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSEMAPHORECREATEINFO_ID 34L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKEVENTCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKEVENTCREATEINFO_ID 35L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKQUERYPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKQUERYPOOLCREATEINFO_ID 36L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERCREATEINFO_ID 37L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERVIEWCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERVIEWCREATEINFO_ID 38L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGECREATEINFO_ID 39L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBRESOURCELAYOUT_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBRESOURCELAYOUT_ID 40L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMPONENTMAPPING_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMPONENTMAPPING_ID 41L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGESUBRESOURCERANGE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGESUBRESOURCERANGE_ID 42L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEVIEWCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEVIEWCREATEINFO_ID 43L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSHADERMODULECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSHADERMODULECREATEINFO_ID 44L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINECACHECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINECACHECREATEINFO_ID 45L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPECIALIZATIONMAPENTRY_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPECIALIZATIONMAPENTRY_ID 46L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPECIALIZATIONINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSPECIALIZATIONINFO_ID 47L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINESHADERSTAGECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINESHADERSTAGECREATEINFO_ID 48L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKVERTEXINPUTBINDINGDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKVERTEXINPUTBINDINGDESCRIPTION_ID 49L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKVERTEXINPUTATTRIBUTEDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKVERTEXINPUTATTRIBUTEDESCRIPTION_ID 50L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEVERTEXINPUTSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEVERTEXINPUTSTATECREATEINFO_ID 51L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEINPUTASSEMBLYSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEINPUTASSEMBLYSTATECREATEINFO_ID 52L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINETESSELLATIONSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINETESSELLATIONSTATECREATEINFO_ID 53L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKVIEWPORT_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKVIEWPORT_ID 54L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKOFFSET2D_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKOFFSET2D_ID 55L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKEXTENT2D_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKEXTENT2D_ID 56L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKRECT2D_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKRECT2D_ID 57L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEVIEWPORTSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEVIEWPORTSTATECREATEINFO_ID 58L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINERASTERIZATIONSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINERASTERIZATIONSTATECREATEINFO_ID 59L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEMULTISAMPLESTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEMULTISAMPLESTATECREATEINFO_ID 60L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSTENCILOPSTATE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSTENCILOPSTATE_ID 61L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEDEPTHSTENCILSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEDEPTHSTENCILSTATECREATEINFO_ID 62L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINECOLORBLENDATTACHMENTSTATE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINECOLORBLENDATTACHMENTSTATE_ID 63L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINECOLORBLENDSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINECOLORBLENDSTATECREATEINFO_ID 64L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEDYNAMICSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINEDYNAMICSTATECREATEINFO_ID 65L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKGRAPHICSPIPELINECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKGRAPHICSPIPELINECREATEINFO_ID 66L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMPUTEPIPELINECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMPUTEPIPELINECREATEINFO_ID 67L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPUSHCONSTANTRANGE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPUSHCONSTANTRANGE_ID 68L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINELAYOUTCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPIPELINELAYOUTCREATEINFO_ID 69L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSAMPLERCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSAMPLERCREATEINFO_ID 70L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORSETLAYOUTBINDING_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORSETLAYOUTBINDING_ID 71L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORSETLAYOUTCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORSETLAYOUTCREATEINFO_ID 72L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORPOOLSIZE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORPOOLSIZE_ID 73L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORPOOLCREATEINFO_ID 74L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORSETALLOCATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORSETALLOCATEINFO_ID 75L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORIMAGEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORIMAGEINFO_ID 76L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORBUFFERINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDESCRIPTORBUFFERINFO_ID 77L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKWRITEDESCRIPTORSET_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKWRITEDESCRIPTORSET_ID 78L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOPYDESCRIPTORSET_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOPYDESCRIPTORSET_ID 79L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKFRAMEBUFFERCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKFRAMEBUFFERCREATEINFO_ID 80L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKATTACHMENTDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKATTACHMENTDESCRIPTION_ID 81L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKATTACHMENTREFERENCE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKATTACHMENTREFERENCE_ID 82L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBPASSDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBPASSDESCRIPTION_ID 83L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBPASSDEPENDENCY_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSUBPASSDEPENDENCY_ID 84L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKRENDERPASSCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKRENDERPASSCREATEINFO_ID 85L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDPOOLCREATEINFO_ID 86L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDBUFFERALLOCATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDBUFFERALLOCATEINFO_ID 87L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDBUFFERINHERITANCEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDBUFFERINHERITANCEINFO_ID 88L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDBUFFERBEGININFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCOMMANDBUFFERBEGININFO_ID 89L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERCOPY_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERCOPY_ID 90L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGESUBRESOURCELAYERS_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGESUBRESOURCELAYERS_ID 91L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGECOPY_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGECOPY_ID 92L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEBLIT_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEBLIT_ID 93L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERIMAGECOPY_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERIMAGECOPY_ID 94L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARDEPTHSTENCILVALUE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARDEPTHSTENCILVALUE_ID 95L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARATTACHMENT_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARATTACHMENT_ID 96L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARRECT_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARRECT_ID 97L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGERESOLVE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGERESOLVE_ID 98L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYBARRIER_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKMEMORYBARRIER_ID 99L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERMEMORYBARRIER_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKBUFFERMEMORYBARRIER_ID 100L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEMEMORYBARRIER_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKIMAGEMEMORYBARRIER_ID 101L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKRENDERPASSBEGININFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKRENDERPASSBEGININFO_ID 102L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPATCHINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPATCHINDIRECTCOMMAND_ID 103L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDRAWINDEXEDINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDRAWINDEXEDINDIRECTCOMMAND_ID 104L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDRAWINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDRAWINDIRECTCOMMAND_ID 105L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSURFACECAPABILITIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSURFACECAPABILITIESKHR_ID 106L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSURFACEFORMATKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSURFACEFORMATKHR_ID 107L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKSWAPCHAINCREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKSWAPCHAINCREATEINFOKHR_ID 108L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKPRESENTINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKPRESENTINFOKHR_ID 109L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPROPERTIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPROPERTIESKHR_ID 110L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYMODEPARAMETERSKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYMODEPARAMETERSKHR_ID 111L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYMODEPROPERTIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYMODEPROPERTIESKHR_ID 112L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYMODECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYMODECREATEINFOKHR_ID 113L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPLANECAPABILITIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPLANECAPABILITIESKHR_ID 114L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPLANEPROPERTIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPLANEPROPERTIESKHR_ID 115L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYSURFACECREATEINFOKHR_ID 116L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPRESENTINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDISPLAYPRESENTINFOKHR_ID 117L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKXLIBSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKXLIBSURFACECREATEINFOKHR_ID 118L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKXCBSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKXCBSURFACECREATEINFOKHR_ID 119L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKWAYLANDSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKWAYLANDSURFACECREATEINFOKHR_ID 120L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKMIRSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKMIRSURFACECREATEINFOKHR_ID 121L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKANDROIDSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKANDROIDSURFACECREATEINFOKHR_ID 122L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKWIN32SURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKWIN32SURFACECREATEINFOKHR_ID 123L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKDEBUGREPORTCALLBACKCREATEINFOEXT_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKDEBUGREPORTCALLBACKCREATEINFOEXT_ID 124L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARVALUE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARVALUE_ID 125L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARCOLORVALUE_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_VKCLEARCOLORVALUE_ID 126L
#undef bor_vulkan_structs_VkPhysicalDeviceLimits_TAG_ID
#define bor_vulkan_structs_VkPhysicalDeviceLimits_TAG_ID 8L
/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxImageDimension1D0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxImageDimension1D0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxImageDimension1D0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxImageDimension1D0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxImageDimension2D0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxImageDimension2D0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxImageDimension2D0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxImageDimension2D0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxImageDimension3D0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxImageDimension3D0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxImageDimension3D0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxImageDimension3D0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxImageDimensionCube0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxImageDimensionCube0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxImageDimensionCube0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxImageDimensionCube0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxImageArrayLayers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxImageArrayLayers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxImageArrayLayers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxImageArrayLayers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTexelBufferElements0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTexelBufferElements0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTexelBufferElements0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTexelBufferElements0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxUniformBufferRange0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxUniformBufferRange0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxUniformBufferRange0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxUniformBufferRange0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxStorageBufferRange0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxStorageBufferRange0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxStorageBufferRange0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxStorageBufferRange0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPushConstantsSize0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPushConstantsSize0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPushConstantsSize0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPushConstantsSize0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxMemoryAllocationCount0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxMemoryAllocationCount0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxMemoryAllocationCount0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxMemoryAllocationCount0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxSamplerAllocationCount0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxSamplerAllocationCount0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxSamplerAllocationCount0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxSamplerAllocationCount0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setBufferImageGranularity0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setBufferImageGranularity0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getBufferImageGranularity0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getBufferImageGranularity0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSparseAddressSpaceSize0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSparseAddressSpaceSize0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSparseAddressSpaceSize0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSparseAddressSpaceSize0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxBoundDescriptorSets0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxBoundDescriptorSets0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxBoundDescriptorSets0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxBoundDescriptorSets0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPerStageDescriptorSamplers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPerStageDescriptorSamplers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPerStageDescriptorSamplers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPerStageDescriptorSamplers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPerStageDescriptorUniformBuffers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPerStageDescriptorUniformBuffers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPerStageDescriptorUniformBuffers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPerStageDescriptorUniformBuffers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPerStageDescriptorStorageBuffers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPerStageDescriptorStorageBuffers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPerStageDescriptorStorageBuffers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPerStageDescriptorStorageBuffers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPerStageDescriptorSampledImages0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPerStageDescriptorSampledImages0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPerStageDescriptorSampledImages0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPerStageDescriptorSampledImages0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPerStageDescriptorStorageImages0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPerStageDescriptorStorageImages0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPerStageDescriptorStorageImages0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPerStageDescriptorStorageImages0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPerStageDescriptorInputAttachments0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPerStageDescriptorInputAttachments0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPerStageDescriptorInputAttachments0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPerStageDescriptorInputAttachments0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxPerStageResources0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxPerStageResources0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxPerStageResources0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxPerStageResources0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetSamplers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetSamplers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetSamplers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetSamplers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetUniformBuffers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetUniformBuffers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetUniformBuffers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetUniformBuffers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetUniformBuffersDynamic0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetUniformBuffersDynamic0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetUniformBuffersDynamic0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetUniformBuffersDynamic0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetStorageBuffers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetStorageBuffers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetStorageBuffers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetStorageBuffers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetStorageBuffersDynamic0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetStorageBuffersDynamic0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetStorageBuffersDynamic0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetStorageBuffersDynamic0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetSampledImages0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetSampledImages0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetSampledImages0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetSampledImages0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetStorageImages0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetStorageImages0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetStorageImages0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetStorageImages0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDescriptorSetInputAttachments0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDescriptorSetInputAttachments0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDescriptorSetInputAttachments0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDescriptorSetInputAttachments0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxVertexInputAttributes0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxVertexInputAttributes0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxVertexInputAttributes0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxVertexInputAttributes0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxVertexInputBindings0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxVertexInputBindings0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxVertexInputBindings0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxVertexInputBindings0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxVertexInputAttributeOffset0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxVertexInputAttributeOffset0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxVertexInputAttributeOffset0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxVertexInputAttributeOffset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxVertexInputBindingStride0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxVertexInputBindingStride0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxVertexInputBindingStride0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxVertexInputBindingStride0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxVertexOutputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxVertexOutputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxVertexOutputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxVertexOutputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationGenerationLevel0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationGenerationLevel0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationGenerationLevel0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationGenerationLevel0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationPatchSize0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationPatchSize0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationPatchSize0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationPatchSize0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationControlPerVertexInputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationControlPerVertexInputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationControlPerVertexInputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationControlPerVertexInputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationControlPerVertexOutputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationControlPerVertexOutputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationControlPerVertexOutputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationControlPerVertexOutputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationControlPerPatchOutputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationControlPerPatchOutputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationControlPerPatchOutputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationControlPerPatchOutputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationControlTotalOutputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationControlTotalOutputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationControlTotalOutputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationControlTotalOutputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationEvaluationInputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationEvaluationInputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationEvaluationInputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationEvaluationInputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTessellationEvaluationOutputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTessellationEvaluationOutputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTessellationEvaluationOutputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTessellationEvaluationOutputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxGeometryShaderInvocations0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxGeometryShaderInvocations0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxGeometryShaderInvocations0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxGeometryShaderInvocations0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxGeometryInputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxGeometryInputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxGeometryInputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxGeometryInputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxGeometryOutputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxGeometryOutputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxGeometryOutputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxGeometryOutputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxGeometryOutputVertices0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxGeometryOutputVertices0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxGeometryOutputVertices0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxGeometryOutputVertices0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxGeometryTotalOutputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxGeometryTotalOutputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxGeometryTotalOutputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxGeometryTotalOutputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxFragmentInputComponents0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxFragmentInputComponents0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxFragmentInputComponents0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxFragmentInputComponents0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxFragmentOutputAttachments0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxFragmentOutputAttachments0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxFragmentOutputAttachments0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxFragmentOutputAttachments0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxFragmentDualSrcAttachments0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxFragmentDualSrcAttachments0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxFragmentDualSrcAttachments0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxFragmentDualSrcAttachments0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxFragmentCombinedOutputResources0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxFragmentCombinedOutputResources0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxFragmentCombinedOutputResources0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxFragmentCombinedOutputResources0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxComputeSharedMemorySize0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxComputeSharedMemorySize0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxComputeSharedMemorySize0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxComputeSharedMemorySize0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxComputeWorkGroupCount0
 * Signature: (Ljava/nio/Buffer;[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxComputeWorkGroupCount0
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxComputeWorkGroupCount0
 * Signature: (Ljava/nio/Buffer;[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxComputeWorkGroupCount0
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxComputeWorkGroupInvocations0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxComputeWorkGroupInvocations0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxComputeWorkGroupInvocations0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxComputeWorkGroupInvocations0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxComputeWorkGroupSize0
 * Signature: (Ljava/nio/Buffer;[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxComputeWorkGroupSize0
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxComputeWorkGroupSize0
 * Signature: (Ljava/nio/Buffer;[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxComputeWorkGroupSize0
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSubPixelPrecisionBits0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSubPixelPrecisionBits0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSubPixelPrecisionBits0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSubPixelPrecisionBits0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSubTexelPrecisionBits0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSubTexelPrecisionBits0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSubTexelPrecisionBits0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSubTexelPrecisionBits0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMipmapPrecisionBits0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMipmapPrecisionBits0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMipmapPrecisionBits0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMipmapPrecisionBits0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDrawIndexedIndexValue0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDrawIndexedIndexValue0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDrawIndexedIndexValue0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDrawIndexedIndexValue0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxDrawIndirectCount0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxDrawIndirectCount0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxDrawIndirectCount0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxDrawIndirectCount0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxSamplerLodBias0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxSamplerLodBias0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxSamplerLodBias0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxSamplerLodBias0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxSamplerAnisotropy0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxSamplerAnisotropy0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxSamplerAnisotropy0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxSamplerAnisotropy0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxViewports0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxViewports0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxViewports0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxViewports0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxViewportDimensions0
 * Signature: (Ljava/nio/Buffer;[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxViewportDimensions0
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxViewportDimensions0
 * Signature: (Ljava/nio/Buffer;[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxViewportDimensions0
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setViewportBoundsRange0
 * Signature: (Ljava/nio/Buffer;[F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setViewportBoundsRange0
  (JNIEnv *, jclass, jobject, jfloatArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getViewportBoundsRange0
 * Signature: (Ljava/nio/Buffer;[F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getViewportBoundsRange0
  (JNIEnv *, jclass, jobject, jfloatArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setViewportSubPixelBits0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setViewportSubPixelBits0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getViewportSubPixelBits0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getViewportSubPixelBits0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMinMemoryMapAlignment0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMinMemoryMapAlignment0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMinMemoryMapAlignment0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMinMemoryMapAlignment0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMinTexelBufferOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMinTexelBufferOffsetAlignment0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMinTexelBufferOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMinTexelBufferOffsetAlignment0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMinUniformBufferOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMinUniformBufferOffsetAlignment0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMinUniformBufferOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMinUniformBufferOffsetAlignment0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMinStorageBufferOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMinStorageBufferOffsetAlignment0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMinStorageBufferOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMinStorageBufferOffsetAlignment0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMinTexelOffset0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMinTexelOffset0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMinTexelOffset0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMinTexelOffset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTexelOffset0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTexelOffset0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTexelOffset0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTexelOffset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMinTexelGatherOffset0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMinTexelGatherOffset0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMinTexelGatherOffset0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMinTexelGatherOffset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxTexelGatherOffset0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxTexelGatherOffset0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxTexelGatherOffset0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxTexelGatherOffset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMinInterpolationOffset0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMinInterpolationOffset0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMinInterpolationOffset0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMinInterpolationOffset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxInterpolationOffset0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxInterpolationOffset0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxInterpolationOffset0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxInterpolationOffset0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSubPixelInterpolationOffsetBits0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSubPixelInterpolationOffsetBits0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSubPixelInterpolationOffsetBits0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSubPixelInterpolationOffsetBits0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxFramebufferWidth0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxFramebufferWidth0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxFramebufferWidth0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxFramebufferWidth0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxFramebufferHeight0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxFramebufferHeight0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxFramebufferHeight0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxFramebufferHeight0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxFramebufferLayers0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxFramebufferLayers0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxFramebufferLayers0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxFramebufferLayers0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setFramebufferColorSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setFramebufferColorSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getFramebufferColorSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getFramebufferColorSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setFramebufferDepthSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setFramebufferDepthSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getFramebufferDepthSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getFramebufferDepthSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setFramebufferStencilSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setFramebufferStencilSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getFramebufferStencilSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getFramebufferStencilSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setFramebufferNoAttachmentsSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setFramebufferNoAttachmentsSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getFramebufferNoAttachmentsSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getFramebufferNoAttachmentsSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxColorAttachments0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxColorAttachments0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxColorAttachments0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxColorAttachments0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSampledImageColorSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSampledImageColorSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSampledImageColorSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSampledImageColorSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSampledImageIntegerSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSampledImageIntegerSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSampledImageIntegerSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSampledImageIntegerSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSampledImageDepthSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSampledImageDepthSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSampledImageDepthSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSampledImageDepthSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setSampledImageStencilSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setSampledImageStencilSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getSampledImageStencilSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getSampledImageStencilSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setStorageImageSampleCounts0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setStorageImageSampleCounts0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getStorageImageSampleCounts0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getStorageImageSampleCounts0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxSampleMaskWords0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxSampleMaskWords0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxSampleMaskWords0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxSampleMaskWords0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setTimestampComputeAndGraphics0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setTimestampComputeAndGraphics0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getTimestampComputeAndGraphics0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getTimestampComputeAndGraphics0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setTimestampPeriod0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setTimestampPeriod0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getTimestampPeriod0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getTimestampPeriod0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxClipDistances0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxClipDistances0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxClipDistances0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxClipDistances0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxCullDistances0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxCullDistances0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxCullDistances0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxCullDistances0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setMaxCombinedClipAndCullDistances0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setMaxCombinedClipAndCullDistances0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getMaxCombinedClipAndCullDistances0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getMaxCombinedClipAndCullDistances0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setDiscreteQueuePriorities0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setDiscreteQueuePriorities0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getDiscreteQueuePriorities0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getDiscreteQueuePriorities0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setPointSizeRange0
 * Signature: (Ljava/nio/Buffer;[F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setPointSizeRange0
  (JNIEnv *, jclass, jobject, jfloatArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getPointSizeRange0
 * Signature: (Ljava/nio/Buffer;[F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getPointSizeRange0
  (JNIEnv *, jclass, jobject, jfloatArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setLineWidthRange0
 * Signature: (Ljava/nio/Buffer;[F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setLineWidthRange0
  (JNIEnv *, jclass, jobject, jfloatArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getLineWidthRange0
 * Signature: (Ljava/nio/Buffer;[F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getLineWidthRange0
  (JNIEnv *, jclass, jobject, jfloatArray);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setPointSizeGranularity0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setPointSizeGranularity0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getPointSizeGranularity0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getPointSizeGranularity0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setLineWidthGranularity0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setLineWidthGranularity0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getLineWidthGranularity0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getLineWidthGranularity0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setStrictLines0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setStrictLines0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getStrictLines0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getStrictLines0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setStandardSampleLocations0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setStandardSampleLocations0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getStandardSampleLocations0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getStandardSampleLocations0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setOptimalBufferCopyOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setOptimalBufferCopyOffsetAlignment0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getOptimalBufferCopyOffsetAlignment0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getOptimalBufferCopyOffsetAlignment0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setOptimalBufferCopyRowPitchAlignment0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setOptimalBufferCopyRowPitchAlignment0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getOptimalBufferCopyRowPitchAlignment0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getOptimalBufferCopyRowPitchAlignment0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    setNonCoherentAtomSize0
 * Signature: (Ljava/nio/Buffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_setNonCoherentAtomSize0
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceLimits
 * Method:    getNonCoherentAtomSize0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceLimits_getNonCoherentAtomSize0
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
