/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bor_vulkan_structs_VkPhysicalDeviceFeatures */

#ifndef _Included_bor_vulkan_structs_VkPhysicalDeviceFeatures
#define _Included_bor_vulkan_structs_VkPhysicalDeviceFeatures
#ifdef __cplusplus
extern "C" {
#endif
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKAPPLICATIONINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKAPPLICATIONINFO_ID 1L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKINSTANCECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKINSTANCECREATEINFO_ID 2L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKALLOCATIONCALLBACKS_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKALLOCATIONCALLBACKS_ID 3L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICEFEATURES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICEFEATURES_ID 4L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKFORMATPROPERTIES_ID 5L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEXTENT3D_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEXTENT3D_ID 6L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEFORMATPROPERTIES_ID 7L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICELIMITS_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICELIMITS_ID 8L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICESPARSEPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICESPARSEPROPERTIES_ID 9L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICEPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICEPROPERTIES_ID 10L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKQUEUEFAMILYPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKQUEUEFAMILYPROPERTIES_ID 11L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYTYPE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYTYPE_ID 12L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYHEAP_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYHEAP_ID 13L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICEMEMORYPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPHYSICALDEVICEMEMORYPROPERTIES_ID 14L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEVICEQUEUECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEVICEQUEUECREATEINFO_ID 15L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEVICECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEVICECREATEINFO_ID 16L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEXTENSIONPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEXTENSIONPROPERTIES_ID 17L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKLAYERPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKLAYERPROPERTIES_ID 18L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBMITINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBMITINFO_ID 19L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYALLOCATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYALLOCATEINFO_ID 20L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMAPPEDMEMORYRANGE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMAPPEDMEMORYRANGE_ID 21L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYREQUIREMENTS_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYREQUIREMENTS_ID 22L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEFORMATPROPERTIES_ID 23L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEMEMORYREQUIREMENTS_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEMEMORYREQUIREMENTS_ID 24L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEMEMORYBIND_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEMEMORYBIND_ID 25L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEBUFFERMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEBUFFERMEMORYBINDINFO_ID 26L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEOPAQUEMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEOPAQUEMEMORYBINDINFO_ID 27L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGESUBRESOURCE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGESUBRESOURCE_ID 28L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKOFFSET3D_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKOFFSET3D_ID 29L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEMEMORYBIND_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEMEMORYBIND_ID 30L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPARSEIMAGEMEMORYBINDINFO_ID 31L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBINDSPARSEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBINDSPARSEINFO_ID 32L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKFENCECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKFENCECREATEINFO_ID 33L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSEMAPHORECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSEMAPHORECREATEINFO_ID 34L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEVENTCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEVENTCREATEINFO_ID 35L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKQUERYPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKQUERYPOOLCREATEINFO_ID 36L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERCREATEINFO_ID 37L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERVIEWCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERVIEWCREATEINFO_ID 38L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGECREATEINFO_ID 39L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBRESOURCELAYOUT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBRESOURCELAYOUT_ID 40L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMPONENTMAPPING_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMPONENTMAPPING_ID 41L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGESUBRESOURCERANGE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGESUBRESOURCERANGE_ID 42L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEVIEWCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEVIEWCREATEINFO_ID 43L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSHADERMODULECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSHADERMODULECREATEINFO_ID 44L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINECACHECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINECACHECREATEINFO_ID 45L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPECIALIZATIONMAPENTRY_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPECIALIZATIONMAPENTRY_ID 46L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPECIALIZATIONINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSPECIALIZATIONINFO_ID 47L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINESHADERSTAGECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINESHADERSTAGECREATEINFO_ID 48L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKVERTEXINPUTBINDINGDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKVERTEXINPUTBINDINGDESCRIPTION_ID 49L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKVERTEXINPUTATTRIBUTEDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKVERTEXINPUTATTRIBUTEDESCRIPTION_ID 50L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEVERTEXINPUTSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEVERTEXINPUTSTATECREATEINFO_ID 51L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEINPUTASSEMBLYSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEINPUTASSEMBLYSTATECREATEINFO_ID 52L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINETESSELLATIONSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINETESSELLATIONSTATECREATEINFO_ID 53L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKVIEWPORT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKVIEWPORT_ID 54L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKOFFSET2D_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKOFFSET2D_ID 55L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEXTENT2D_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKEXTENT2D_ID 56L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKRECT2D_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKRECT2D_ID 57L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEVIEWPORTSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEVIEWPORTSTATECREATEINFO_ID 58L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINERASTERIZATIONSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINERASTERIZATIONSTATECREATEINFO_ID 59L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEMULTISAMPLESTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEMULTISAMPLESTATECREATEINFO_ID 60L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSTENCILOPSTATE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSTENCILOPSTATE_ID 61L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEDEPTHSTENCILSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEDEPTHSTENCILSTATECREATEINFO_ID 62L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINECOLORBLENDATTACHMENTSTATE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINECOLORBLENDATTACHMENTSTATE_ID 63L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINECOLORBLENDSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINECOLORBLENDSTATECREATEINFO_ID 64L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEDYNAMICSTATECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINEDYNAMICSTATECREATEINFO_ID 65L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKGRAPHICSPIPELINECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKGRAPHICSPIPELINECREATEINFO_ID 66L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMPUTEPIPELINECREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMPUTEPIPELINECREATEINFO_ID 67L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPUSHCONSTANTRANGE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPUSHCONSTANTRANGE_ID 68L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINELAYOUTCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINELAYOUTCREATEINFO_ID 69L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSAMPLERCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSAMPLERCREATEINFO_ID 70L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORSETLAYOUTBINDING_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORSETLAYOUTBINDING_ID 71L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORSETLAYOUTCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORSETLAYOUTCREATEINFO_ID 72L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORPOOLSIZE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORPOOLSIZE_ID 73L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORPOOLCREATEINFO_ID 74L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORSETALLOCATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORSETALLOCATEINFO_ID 75L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORIMAGEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORIMAGEINFO_ID 76L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORBUFFERINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDESCRIPTORBUFFERINFO_ID 77L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKWRITEDESCRIPTORSET_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKWRITEDESCRIPTORSET_ID 78L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOPYDESCRIPTORSET_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOPYDESCRIPTORSET_ID 79L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKFRAMEBUFFERCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKFRAMEBUFFERCREATEINFO_ID 80L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKATTACHMENTDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKATTACHMENTDESCRIPTION_ID 81L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKATTACHMENTREFERENCE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKATTACHMENTREFERENCE_ID 82L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBPASSDESCRIPTION_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBPASSDESCRIPTION_ID 83L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBPASSDEPENDENCY_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSUBPASSDEPENDENCY_ID 84L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKRENDERPASSCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKRENDERPASSCREATEINFO_ID 85L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDPOOLCREATEINFO_ID 86L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDBUFFERALLOCATEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDBUFFERALLOCATEINFO_ID 87L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDBUFFERINHERITANCEINFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDBUFFERINHERITANCEINFO_ID 88L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDBUFFERBEGININFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCOMMANDBUFFERBEGININFO_ID 89L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERCOPY_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERCOPY_ID 90L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGESUBRESOURCELAYERS_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGESUBRESOURCELAYERS_ID 91L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGECOPY_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGECOPY_ID 92L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEBLIT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEBLIT_ID 93L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERIMAGECOPY_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERIMAGECOPY_ID 94L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARDEPTHSTENCILVALUE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARDEPTHSTENCILVALUE_ID 95L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARATTACHMENT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARATTACHMENT_ID 96L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARRECT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARRECT_ID 97L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGERESOLVE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGERESOLVE_ID 98L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYBARRIER_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMEMORYBARRIER_ID 99L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERMEMORYBARRIER_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKBUFFERMEMORYBARRIER_ID 100L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEMEMORYBARRIER_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKIMAGEMEMORYBARRIER_ID 101L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKRENDERPASSBEGININFO_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKRENDERPASSBEGININFO_ID 102L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPATCHINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPATCHINDIRECTCOMMAND_ID 103L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDRAWINDEXEDINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDRAWINDEXEDINDIRECTCOMMAND_ID 104L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDRAWINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDRAWINDIRECTCOMMAND_ID 105L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSURFACECAPABILITIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSURFACECAPABILITIESKHR_ID 106L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSURFACEFORMATKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSURFACEFORMATKHR_ID 107L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSWAPCHAINCREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKSWAPCHAINCREATEINFOKHR_ID 108L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPRESENTINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPRESENTINFOKHR_ID 109L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPROPERTIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPROPERTIESKHR_ID 110L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYMODEPARAMETERSKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYMODEPARAMETERSKHR_ID 111L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYMODEPROPERTIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYMODEPROPERTIESKHR_ID 112L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYMODECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYMODECREATEINFOKHR_ID 113L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPLANECAPABILITIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPLANECAPABILITIESKHR_ID 114L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPLANEPROPERTIESKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPLANEPROPERTIESKHR_ID 115L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYSURFACECREATEINFOKHR_ID 116L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPRESENTINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDISPLAYPRESENTINFOKHR_ID 117L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKXLIBSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKXLIBSURFACECREATEINFOKHR_ID 118L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKXCBSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKXCBSURFACECREATEINFOKHR_ID 119L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKWAYLANDSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKWAYLANDSURFACECREATEINFOKHR_ID 120L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMIRSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKMIRSURFACECREATEINFOKHR_ID 121L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKANDROIDSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKANDROIDSURFACECREATEINFOKHR_ID 122L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKWIN32SURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKWIN32SURFACECREATEINFOKHR_ID 123L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGREPORTCALLBACKCREATEINFOEXT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGREPORTCALLBACKCREATEINFOEXT_ID 124L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINERASTERIZATIONSTATERASTERIZATIONORDERAMD_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKPIPELINERASTERIZATIONSTATERASTERIZATIONORDERAMD_ID 125L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGMARKEROBJECTNAMEINFOEXT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGMARKEROBJECTNAMEINFOEXT_ID 126L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGMARKEROBJECTTAGINFOEXT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGMARKEROBJECTTAGINFOEXT_ID 127L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGMARKERMARKERINFOEXT_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEBUGMARKERMARKERINFOEXT_ID 128L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEDICATEDALLOCATIONIMAGECREATEINFONV_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEDICATEDALLOCATIONIMAGECREATEINFONV_ID 129L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEDICATEDALLOCATIONBUFFERCREATEINFONV_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEDICATEDALLOCATIONBUFFERCREATEINFONV_ID 130L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEDICATEDALLOCATIONMEMORYALLOCATEINFONV_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKDEDICATEDALLOCATIONMEMORYALLOCATEINFONV_ID 131L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARVALUE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARVALUE_ID 200L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARCOLORVALUE_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_VKCLEARCOLORVALUE_ID 201L
#undef bor_vulkan_structs_VkPhysicalDeviceFeatures_TAG_ID
#define bor_vulkan_structs_VkPhysicalDeviceFeatures_TAG_ID 4L
/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setRobustBufferAccess0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setRobustBufferAccess0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getRobustBufferAccess0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getRobustBufferAccess0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setFullDrawIndexUint320
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setFullDrawIndexUint320
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getFullDrawIndexUint320
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getFullDrawIndexUint320
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setImageCubeArray0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setImageCubeArray0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getImageCubeArray0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getImageCubeArray0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setIndependentBlend0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setIndependentBlend0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getIndependentBlend0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getIndependentBlend0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setGeometryShader0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setGeometryShader0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getGeometryShader0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getGeometryShader0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setTessellationShader0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setTessellationShader0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getTessellationShader0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getTessellationShader0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSampleRateShading0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSampleRateShading0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSampleRateShading0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSampleRateShading0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setDualSrcBlend0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setDualSrcBlend0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getDualSrcBlend0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getDualSrcBlend0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setLogicOp0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setLogicOp0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getLogicOp0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getLogicOp0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setMultiDrawIndirect0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setMultiDrawIndirect0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getMultiDrawIndirect0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getMultiDrawIndirect0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setDrawIndirectFirstInstance0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setDrawIndirectFirstInstance0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getDrawIndirectFirstInstance0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getDrawIndirectFirstInstance0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setDepthClamp0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setDepthClamp0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getDepthClamp0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getDepthClamp0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setDepthBiasClamp0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setDepthBiasClamp0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getDepthBiasClamp0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getDepthBiasClamp0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setFillModeNonSolid0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setFillModeNonSolid0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getFillModeNonSolid0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getFillModeNonSolid0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setDepthBounds0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setDepthBounds0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getDepthBounds0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getDepthBounds0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setWideLines0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setWideLines0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getWideLines0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getWideLines0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setLargePoints0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setLargePoints0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getLargePoints0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getLargePoints0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setAlphaToOne0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setAlphaToOne0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getAlphaToOne0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getAlphaToOne0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setMultiViewport0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setMultiViewport0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getMultiViewport0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getMultiViewport0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSamplerAnisotropy0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSamplerAnisotropy0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSamplerAnisotropy0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSamplerAnisotropy0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setTextureCompressionETC20
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setTextureCompressionETC20
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getTextureCompressionETC20
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getTextureCompressionETC20
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setTextureCompressionASTCJLDR0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setTextureCompressionASTCJLDR0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getTextureCompressionASTCJLDR0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getTextureCompressionASTCJLDR0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setTextureCompressionBC0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setTextureCompressionBC0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getTextureCompressionBC0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getTextureCompressionBC0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setOcclusionQueryPrecise0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setOcclusionQueryPrecise0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getOcclusionQueryPrecise0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getOcclusionQueryPrecise0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setPipelineStatisticsQuery0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setPipelineStatisticsQuery0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getPipelineStatisticsQuery0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getPipelineStatisticsQuery0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setVertexPipelineStoresAndAtomics0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setVertexPipelineStoresAndAtomics0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getVertexPipelineStoresAndAtomics0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getVertexPipelineStoresAndAtomics0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setFragmentStoresAndAtomics0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setFragmentStoresAndAtomics0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getFragmentStoresAndAtomics0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getFragmentStoresAndAtomics0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderTessellationAndGeometryPointSize0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderTessellationAndGeometryPointSize0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderTessellationAndGeometryPointSize0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderTessellationAndGeometryPointSize0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderImageGatherExtended0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderImageGatherExtended0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderImageGatherExtended0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderImageGatherExtended0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderStorageImageExtendedFormats0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderStorageImageExtendedFormats0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderStorageImageExtendedFormats0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderStorageImageExtendedFormats0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderStorageImageMultisample0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderStorageImageMultisample0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderStorageImageMultisample0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderStorageImageMultisample0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderStorageImageReadWithoutFormat0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderStorageImageReadWithoutFormat0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderStorageImageReadWithoutFormat0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderStorageImageReadWithoutFormat0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderStorageImageWriteWithoutFormat0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderStorageImageWriteWithoutFormat0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderStorageImageWriteWithoutFormat0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderStorageImageWriteWithoutFormat0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderUniformBufferArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderUniformBufferArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderUniformBufferArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderUniformBufferArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderSampledImageArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderSampledImageArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderSampledImageArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderSampledImageArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderStorageBufferArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderStorageBufferArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderStorageBufferArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderStorageBufferArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderStorageImageArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderStorageImageArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderStorageImageArrayDynamicIndexing0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderStorageImageArrayDynamicIndexing0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderClipDistance0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderClipDistance0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderClipDistance0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderClipDistance0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderCullDistance0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderCullDistance0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderCullDistance0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderCullDistance0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderFloat640
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderFloat640
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderFloat640
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderFloat640
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderInt640
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderInt640
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderInt640
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderInt640
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderInt160
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderInt160
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderInt160
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderInt160
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderResourceResidency0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderResourceResidency0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderResourceResidency0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderResourceResidency0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setShaderResourceMinLod0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setShaderResourceMinLod0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getShaderResourceMinLod0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getShaderResourceMinLod0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseBinding0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseBinding0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseBinding0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseBinding0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidencyBuffer0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidencyBuffer0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidencyBuffer0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidencyBuffer0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidencyImage2D0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidencyImage2D0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidencyImage2D0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidencyImage2D0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidencyImage3D0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidencyImage3D0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidencyImage3D0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidencyImage3D0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidency2Samples0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidency2Samples0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidency2Samples0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidency2Samples0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidency4Samples0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidency4Samples0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidency4Samples0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidency4Samples0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidency8Samples0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidency8Samples0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidency8Samples0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidency8Samples0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidency16Samples0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidency16Samples0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidency16Samples0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidency16Samples0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setSparseResidencyAliased0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setSparseResidencyAliased0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getSparseResidencyAliased0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getSparseResidencyAliased0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setVariableMultisampleRate0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setVariableMultisampleRate0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getVariableMultisampleRate0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getVariableMultisampleRate0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    setInheritedQueries0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_setInheritedQueries0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkPhysicalDeviceFeatures
 * Method:    getInheritedQueries0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkPhysicalDeviceFeatures_getInheritedQueries0
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
