/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bor_vulkan_structs_VkSamplerCreateInfo */

#ifndef _Included_bor_vulkan_structs_VkSamplerCreateInfo
#define _Included_bor_vulkan_structs_VkSamplerCreateInfo
#ifdef __cplusplus
extern "C" {
#endif
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKAPPLICATIONINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKAPPLICATIONINFO_ID 1L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKINSTANCECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKINSTANCECREATEINFO_ID 2L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKALLOCATIONCALLBACKS_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKALLOCATIONCALLBACKS_ID 3L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICEFEATURES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICEFEATURES_ID 4L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKFORMATPROPERTIES_ID 5L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKEXTENT3D_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKEXTENT3D_ID 6L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEFORMATPROPERTIES_ID 7L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICELIMITS_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICELIMITS_ID 8L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICESPARSEPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICESPARSEPROPERTIES_ID 9L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICEPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICEPROPERTIES_ID 10L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKQUEUEFAMILYPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKQUEUEFAMILYPROPERTIES_ID 11L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYTYPE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYTYPE_ID 12L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYHEAP_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYHEAP_ID 13L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICEMEMORYPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPHYSICALDEVICEMEMORYPROPERTIES_ID 14L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEVICEQUEUECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEVICEQUEUECREATEINFO_ID 15L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEVICECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEVICECREATEINFO_ID 16L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKEXTENSIONPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKEXTENSIONPROPERTIES_ID 17L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKLAYERPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKLAYERPROPERTIES_ID 18L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSUBMITINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSUBMITINFO_ID 19L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYALLOCATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYALLOCATEINFO_ID 20L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKMAPPEDMEMORYRANGE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKMAPPEDMEMORYRANGE_ID 21L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYREQUIREMENTS_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYREQUIREMENTS_ID 22L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEFORMATPROPERTIES_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEFORMATPROPERTIES_ID 23L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEMEMORYREQUIREMENTS_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEMEMORYREQUIREMENTS_ID 24L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEMEMORYBIND_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEMEMORYBIND_ID 25L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEBUFFERMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEBUFFERMEMORYBINDINFO_ID 26L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEOPAQUEMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEOPAQUEMEMORYBINDINFO_ID 27L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGESUBRESOURCE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGESUBRESOURCE_ID 28L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKOFFSET3D_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKOFFSET3D_ID 29L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEMEMORYBIND_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEMEMORYBIND_ID 30L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEMEMORYBINDINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPARSEIMAGEMEMORYBINDINFO_ID 31L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKBINDSPARSEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKBINDSPARSEINFO_ID 32L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKFENCECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKFENCECREATEINFO_ID 33L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSEMAPHORECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSEMAPHORECREATEINFO_ID 34L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKEVENTCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKEVENTCREATEINFO_ID 35L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKQUERYPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKQUERYPOOLCREATEINFO_ID 36L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERCREATEINFO_ID 37L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERVIEWCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERVIEWCREATEINFO_ID 38L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGECREATEINFO_ID 39L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSUBRESOURCELAYOUT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSUBRESOURCELAYOUT_ID 40L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCOMPONENTMAPPING_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCOMPONENTMAPPING_ID 41L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGESUBRESOURCERANGE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGESUBRESOURCERANGE_ID 42L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEVIEWCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEVIEWCREATEINFO_ID 43L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSHADERMODULECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSHADERMODULECREATEINFO_ID 44L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINECACHECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINECACHECREATEINFO_ID 45L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPECIALIZATIONMAPENTRY_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPECIALIZATIONMAPENTRY_ID 46L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSPECIALIZATIONINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSPECIALIZATIONINFO_ID 47L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINESHADERSTAGECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINESHADERSTAGECREATEINFO_ID 48L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKVERTEXINPUTBINDINGDESCRIPTION_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKVERTEXINPUTBINDINGDESCRIPTION_ID 49L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKVERTEXINPUTATTRIBUTEDESCRIPTION_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKVERTEXINPUTATTRIBUTEDESCRIPTION_ID 50L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEVERTEXINPUTSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEVERTEXINPUTSTATECREATEINFO_ID 51L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEINPUTASSEMBLYSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEINPUTASSEMBLYSTATECREATEINFO_ID 52L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINETESSELLATIONSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINETESSELLATIONSTATECREATEINFO_ID 53L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKVIEWPORT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKVIEWPORT_ID 54L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKOFFSET2D_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKOFFSET2D_ID 55L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKEXTENT2D_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKEXTENT2D_ID 56L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKRECT2D_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKRECT2D_ID 57L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEVIEWPORTSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEVIEWPORTSTATECREATEINFO_ID 58L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINERASTERIZATIONSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINERASTERIZATIONSTATECREATEINFO_ID 59L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEMULTISAMPLESTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEMULTISAMPLESTATECREATEINFO_ID 60L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSTENCILOPSTATE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSTENCILOPSTATE_ID 61L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEDEPTHSTENCILSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEDEPTHSTENCILSTATECREATEINFO_ID 62L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINECOLORBLENDATTACHMENTSTATE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINECOLORBLENDATTACHMENTSTATE_ID 63L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINECOLORBLENDSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINECOLORBLENDSTATECREATEINFO_ID 64L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEDYNAMICSTATECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINEDYNAMICSTATECREATEINFO_ID 65L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKGRAPHICSPIPELINECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKGRAPHICSPIPELINECREATEINFO_ID 66L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCOMPUTEPIPELINECREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCOMPUTEPIPELINECREATEINFO_ID 67L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPUSHCONSTANTRANGE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPUSHCONSTANTRANGE_ID 68L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINELAYOUTCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINELAYOUTCREATEINFO_ID 69L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSAMPLERCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSAMPLERCREATEINFO_ID 70L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORSETLAYOUTBINDING_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORSETLAYOUTBINDING_ID 71L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORSETLAYOUTCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORSETLAYOUTCREATEINFO_ID 72L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORPOOLSIZE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORPOOLSIZE_ID 73L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORPOOLCREATEINFO_ID 74L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORSETALLOCATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORSETALLOCATEINFO_ID 75L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORIMAGEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORIMAGEINFO_ID 76L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORBUFFERINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDESCRIPTORBUFFERINFO_ID 77L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKWRITEDESCRIPTORSET_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKWRITEDESCRIPTORSET_ID 78L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCOPYDESCRIPTORSET_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCOPYDESCRIPTORSET_ID 79L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKFRAMEBUFFERCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKFRAMEBUFFERCREATEINFO_ID 80L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKATTACHMENTDESCRIPTION_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKATTACHMENTDESCRIPTION_ID 81L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKATTACHMENTREFERENCE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKATTACHMENTREFERENCE_ID 82L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSUBPASSDESCRIPTION_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSUBPASSDESCRIPTION_ID 83L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSUBPASSDEPENDENCY_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSUBPASSDEPENDENCY_ID 84L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKRENDERPASSCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKRENDERPASSCREATEINFO_ID 85L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDPOOLCREATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDPOOLCREATEINFO_ID 86L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDBUFFERALLOCATEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDBUFFERALLOCATEINFO_ID 87L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDBUFFERINHERITANCEINFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDBUFFERINHERITANCEINFO_ID 88L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDBUFFERBEGININFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCOMMANDBUFFERBEGININFO_ID 89L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERCOPY_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERCOPY_ID 90L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGESUBRESOURCELAYERS_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGESUBRESOURCELAYERS_ID 91L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGECOPY_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGECOPY_ID 92L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEBLIT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEBLIT_ID 93L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERIMAGECOPY_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERIMAGECOPY_ID 94L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARDEPTHSTENCILVALUE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARDEPTHSTENCILVALUE_ID 95L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARATTACHMENT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARATTACHMENT_ID 96L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARRECT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARRECT_ID 97L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGERESOLVE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGERESOLVE_ID 98L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYBARRIER_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKMEMORYBARRIER_ID 99L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERMEMORYBARRIER_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKBUFFERMEMORYBARRIER_ID 100L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEMEMORYBARRIER_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKIMAGEMEMORYBARRIER_ID 101L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKRENDERPASSBEGININFO_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKRENDERPASSBEGININFO_ID 102L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPATCHINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPATCHINDIRECTCOMMAND_ID 103L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDRAWINDEXEDINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDRAWINDEXEDINDIRECTCOMMAND_ID 104L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDRAWINDIRECTCOMMAND_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDRAWINDIRECTCOMMAND_ID 105L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSURFACECAPABILITIESKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSURFACECAPABILITIESKHR_ID 106L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSURFACEFORMATKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSURFACEFORMATKHR_ID 107L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKSWAPCHAINCREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKSWAPCHAINCREATEINFOKHR_ID 108L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPRESENTINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPRESENTINFOKHR_ID 109L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPROPERTIESKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPROPERTIESKHR_ID 110L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYMODEPARAMETERSKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYMODEPARAMETERSKHR_ID 111L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYMODEPROPERTIESKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYMODEPROPERTIESKHR_ID 112L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYMODECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYMODECREATEINFOKHR_ID 113L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPLANECAPABILITIESKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPLANECAPABILITIESKHR_ID 114L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPLANEPROPERTIESKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPLANEPROPERTIESKHR_ID 115L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYSURFACECREATEINFOKHR_ID 116L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPRESENTINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDISPLAYPRESENTINFOKHR_ID 117L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKXLIBSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKXLIBSURFACECREATEINFOKHR_ID 118L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKXCBSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKXCBSURFACECREATEINFOKHR_ID 119L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKWAYLANDSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKWAYLANDSURFACECREATEINFOKHR_ID 120L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKMIRSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKMIRSURFACECREATEINFOKHR_ID 121L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKANDROIDSURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKANDROIDSURFACECREATEINFOKHR_ID 122L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKWIN32SURFACECREATEINFOKHR_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKWIN32SURFACECREATEINFOKHR_ID 123L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGREPORTCALLBACKCREATEINFOEXT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGREPORTCALLBACKCREATEINFOEXT_ID 124L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINERASTERIZATIONSTATERASTERIZATIONORDERAMD_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKPIPELINERASTERIZATIONSTATERASTERIZATIONORDERAMD_ID 125L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGMARKEROBJECTNAMEINFOEXT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGMARKEROBJECTNAMEINFOEXT_ID 126L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGMARKEROBJECTTAGINFOEXT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGMARKEROBJECTTAGINFOEXT_ID 127L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGMARKERMARKERINFOEXT_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEBUGMARKERMARKERINFOEXT_ID 128L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEDICATEDALLOCATIONIMAGECREATEINFONV_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEDICATEDALLOCATIONIMAGECREATEINFONV_ID 129L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEDICATEDALLOCATIONBUFFERCREATEINFONV_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEDICATEDALLOCATIONBUFFERCREATEINFONV_ID 130L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKDEDICATEDALLOCATIONMEMORYALLOCATEINFONV_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKDEDICATEDALLOCATIONMEMORYALLOCATEINFONV_ID 131L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARVALUE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARVALUE_ID 200L
#undef bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARCOLORVALUE_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_VKCLEARCOLORVALUE_ID 201L
#undef bor_vulkan_structs_VkSamplerCreateInfo_TAG_ID
#define bor_vulkan_structs_VkSamplerCreateInfo_TAG_ID 70L
/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setSType0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setSType0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getSType0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getSType0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setPNext0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setPNext0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getPNext0
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getPNext0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setFlags0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setFlags0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getFlags0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getFlags0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setMagFilter0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setMagFilter0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getMagFilter0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getMagFilter0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setMinFilter0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setMinFilter0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getMinFilter0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getMinFilter0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setMipmapMode0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setMipmapMode0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getMipmapMode0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getMipmapMode0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setAddressModeU0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setAddressModeU0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getAddressModeU0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getAddressModeU0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setAddressModeV0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setAddressModeV0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getAddressModeV0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getAddressModeV0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setAddressModeW0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setAddressModeW0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getAddressModeW0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getAddressModeW0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setMipLodBias0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setMipLodBias0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getMipLodBias0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getMipLodBias0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setAnisotropyEnable0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setAnisotropyEnable0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getAnisotropyEnable0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getAnisotropyEnable0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setMaxAnisotropy0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setMaxAnisotropy0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getMaxAnisotropy0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getMaxAnisotropy0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setCompareEnable0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setCompareEnable0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getCompareEnable0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getCompareEnable0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setCompareOp0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setCompareOp0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getCompareOp0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getCompareOp0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setMinLod0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setMinLod0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getMinLod0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getMinLod0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setMaxLod0
 * Signature: (Ljava/nio/Buffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setMaxLod0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getMaxLod0
 * Signature: (Ljava/nio/Buffer;)F
 */
JNIEXPORT jfloat JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getMaxLod0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setBorderColor0
 * Signature: (Ljava/nio/Buffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setBorderColor0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getBorderColor0
 * Signature: (Ljava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getBorderColor0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    setUnnormalizedCoordinates0
 * Signature: (Ljava/nio/Buffer;Z)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_setUnnormalizedCoordinates0
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     bor_vulkan_structs_VkSamplerCreateInfo
 * Method:    getUnnormalizedCoordinates0
 * Signature: (Ljava/nio/Buffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_structs_VkSamplerCreateInfo_getUnnormalizedCoordinates0
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
