/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bor_util_Utils */

#ifndef _Included_bor_util_Utils
#define _Included_bor_util_Utils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bor_util_Utils
 * Method:    sizeOfPtr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bor_util_Utils_sizeOfPtr
  (JNIEnv *, jclass);

/*
 * Class:     bor_util_Utils
 * Method:    equals
 * Signature: (Ljava/nio/Buffer;J)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_util_Utils_equals
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     bor_util_Utils
 * Method:    getNativeAddress
 * Signature: (Ljava/nio/Buffer;)J
 */
JNIEXPORT jlong JNICALL Java_bor_util_Utils_getNativeAddress
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_util_Utils
 * Method:    wrapPointer
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_util_Utils_wrapPointer
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     bor_util_Utils
 * Method:    createNativeDirectBuffer
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_util_Utils_createNativeDirectBuffer
  (JNIEnv *, jclass, jint);

/*
 * Class:     bor_util_Utils
 * Method:    deleteDirectBuffer
 * Signature: (Ljava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_bor_util_Utils_deleteDirectBuffer
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
