/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bor_vulkan_Vk10 */

#ifndef _Included_bor_vulkan_Vk10
#define _Included_bor_vulkan_Vk10
#ifdef __cplusplus
extern "C" {
#endif
#undef bor_vulkan_Vk10_VK_LOD_CLAMP_NONE
#define bor_vulkan_Vk10_VK_LOD_CLAMP_NONE 1000.0f
#undef bor_vulkan_Vk10_VK_REMAINING_MIP_LEVELS
#define bor_vulkan_Vk10_VK_REMAINING_MIP_LEVELS 2147483647L
#undef bor_vulkan_Vk10_VK_REMAINING_ARRAY_LAYERS
#define bor_vulkan_Vk10_VK_REMAINING_ARRAY_LAYERS 2147483647L
#undef bor_vulkan_Vk10_VK_WHOLE_SIZE
#define bor_vulkan_Vk10_VK_WHOLE_SIZE 9223372036854775807i64
#undef bor_vulkan_Vk10_VK_ATTACHMENT_UNUSED
#define bor_vulkan_Vk10_VK_ATTACHMENT_UNUSED 2147483647L
#undef bor_vulkan_Vk10_VK_TRUE
#define bor_vulkan_Vk10_VK_TRUE 1L
#undef bor_vulkan_Vk10_VK_FALSE
#define bor_vulkan_Vk10_VK_FALSE 0L
#undef bor_vulkan_Vk10_VK_QUEUE_FAMILY_IGNORED
#define bor_vulkan_Vk10_VK_QUEUE_FAMILY_IGNORED 2147483647L
#undef bor_vulkan_Vk10_VK_SUBPASS_EXTERNAL
#define bor_vulkan_Vk10_VK_SUBPASS_EXTERNAL 2147483647L
#undef bor_vulkan_Vk10_VK_MAX_PHYSICAL_DEVICE_NAME_SIZE
#define bor_vulkan_Vk10_VK_MAX_PHYSICAL_DEVICE_NAME_SIZE 256L
#undef bor_vulkan_Vk10_VK_UUID_SIZE
#define bor_vulkan_Vk10_VK_UUID_SIZE 16L
#undef bor_vulkan_Vk10_VK_MAX_MEMORY_TYPES
#define bor_vulkan_Vk10_VK_MAX_MEMORY_TYPES 32L
#undef bor_vulkan_Vk10_VK_MAX_MEMORY_HEAPS
#define bor_vulkan_Vk10_VK_MAX_MEMORY_HEAPS 16L
#undef bor_vulkan_Vk10_VK_MAX_EXTENSION_NAME_SIZE
#define bor_vulkan_Vk10_VK_MAX_EXTENSION_NAME_SIZE 256L
#undef bor_vulkan_Vk10_VK_MAX_DESCRIPTION_SIZE
#define bor_vulkan_Vk10_VK_MAX_DESCRIPTION_SIZE 256L
#undef bor_vulkan_Vk10_VK_KHR_surface
#define bor_vulkan_Vk10_VK_KHR_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_SURFACE_SPEC_VERSION 25L
#undef bor_vulkan_Vk10_VK_KHR_swapchain
#define bor_vulkan_Vk10_VK_KHR_swapchain 1L
#undef bor_vulkan_Vk10_VK_KHR_SWAPCHAIN_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_SWAPCHAIN_SPEC_VERSION 67L
#undef bor_vulkan_Vk10_VK_KHR_display
#define bor_vulkan_Vk10_VK_KHR_display 1L
#undef bor_vulkan_Vk10_VK_KHR_DISPLAY_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_DISPLAY_SPEC_VERSION 21L
#undef bor_vulkan_Vk10_VK_KHR_display_swapchain
#define bor_vulkan_Vk10_VK_KHR_display_swapchain 1L
#undef bor_vulkan_Vk10_VK_KHR_DISPLAY_SWAPCHAIN_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_DISPLAY_SWAPCHAIN_SPEC_VERSION 9L
#undef bor_vulkan_Vk10_VK_KHR_xlib_surface
#define bor_vulkan_Vk10_VK_KHR_xlib_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_XLIB_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_XLIB_SURFACE_SPEC_VERSION 6L
#undef bor_vulkan_Vk10_VK_KHR_xcb_surface
#define bor_vulkan_Vk10_VK_KHR_xcb_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_XCB_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_XCB_SURFACE_SPEC_VERSION 6L
#undef bor_vulkan_Vk10_VK_KHR_wayland_surface
#define bor_vulkan_Vk10_VK_KHR_wayland_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_WAYLAND_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_WAYLAND_SURFACE_SPEC_VERSION 5L
#undef bor_vulkan_Vk10_VK_KHR_mir_surface
#define bor_vulkan_Vk10_VK_KHR_mir_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_MIR_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_MIR_SURFACE_SPEC_VERSION 4L
#undef bor_vulkan_Vk10_VK_KHR_android_surface
#define bor_vulkan_Vk10_VK_KHR_android_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_ANDROID_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_ANDROID_SURFACE_SPEC_VERSION 6L
#undef bor_vulkan_Vk10_VK_KHR_win32_surface
#define bor_vulkan_Vk10_VK_KHR_win32_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_WIN32_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_WIN32_SURFACE_SPEC_VERSION 5L
#undef bor_vulkan_Vk10_VK_EXT_debug_report
#define bor_vulkan_Vk10_VK_EXT_debug_report 1L
#undef bor_vulkan_Vk10_VK_EXT_DEBUG_REPORT_SPEC_VERSION
#define bor_vulkan_Vk10_VK_EXT_DEBUG_REPORT_SPEC_VERSION 2L
#undef bor_vulkan_Vk10_VK_KHR_sampler_mirror_clamp_to_edge
#define bor_vulkan_Vk10_VK_KHR_sampler_mirror_clamp_to_edge 1L
#undef bor_vulkan_Vk10_VK_KHR_SAMPLER_MIRROR_CLAMP_TO_EDGE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_SAMPLER_MIRROR_CLAMP_TO_EDGE_SPEC_VERSION 1L
#undef bor_vulkan_Vk10_VK_NV_glsl_shader
#define bor_vulkan_Vk10_VK_NV_glsl_shader 1L
#undef bor_vulkan_Vk10_VK_NV_GLSL_SHADER_SPEC_VERSION
#define bor_vulkan_Vk10_VK_NV_GLSL_SHADER_SPEC_VERSION 1L
#undef bor_vulkan_Vk10_VK_IMG_filter_cubic
#define bor_vulkan_Vk10_VK_IMG_filter_cubic 1L
#undef bor_vulkan_Vk10_VK_IMG_FILTER_CUBIC_SPEC_VERSION
#define bor_vulkan_Vk10_VK_IMG_FILTER_CUBIC_SPEC_VERSION 1L
/*
 * Class:     bor_vulkan_Vk10
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_init
  (JNIEnv *, jclass);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    sizeOfDispatchableHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_sizeOfDispatchableHandle
  (JNIEnv *, jclass);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    sizeOfNonDispatchableHandle
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_sizeOfNonDispatchableHandle
  (JNIEnv *, jclass);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    isVulkanAvailable
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_bor_vulkan_Vk10_isVulkanAvailable
  (JNIEnv *, jclass);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateInstance1
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateInstance1
  (JNIEnv *, jclass, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyInstance0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyInstance0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumeratePhysicalDevices0
 * Signature: (Ljava/nio/ByteBuffer;[I[Ljava/nio/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkEnumeratePhysicalDevices0
  (JNIEnv *, jclass, jobject, jintArray, jobjectArray, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceFeatures0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceFeatures0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceFormatProperties0
 * Signature: (Ljava/nio/Buffer;ILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceFormatProperties0
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceImageFormatProperties0
 * Signature: (Ljava/nio/Buffer;IIIIILjava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceImageFormatProperties0
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceProperties0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceProperties0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceQueueFamilyProperties1
 * Signature: (Ljava/nio/ByteBuffer;[ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceQueueFamilyProperties1
  (JNIEnv *, jclass, jobject, jintArray, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceMemoryProperties0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceMemoryProperties0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetInstanceProcAddr0
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkGetInstanceProcAddr0
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetDeviceProcAddr0
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkGetDeviceProcAddr0
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateDevice0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateDevice0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyDevice0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyDevice0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateInstanceExtensionProperties0
 * Signature: (Ljava/lang/String;[ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkEnumerateInstanceExtensionProperties0
  (JNIEnv *, jclass, jstring, jintArray, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateDeviceExtensionProperties0
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;[ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkEnumerateDeviceExtensionProperties0
  (JNIEnv *, jclass, jobject, jstring, jintArray, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateInstanceLayerProperties0
 * Signature: ([ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkEnumerateInstanceLayerProperties0
  (JNIEnv *, jclass, jintArray, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateDeviceLayerProperties0
 * Signature: (Ljava/nio/Buffer;[ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkEnumerateDeviceLayerProperties0
  (JNIEnv *, jclass, jobject, jintArray, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetDeviceQueue0
 * Signature: (Ljava/nio/Buffer;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkGetDeviceQueue0
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkQueueSubmit0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkQueueSubmit0
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkQueueWaitIdle0
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkQueueWaitIdle0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDeviceWaitIdle0
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkDeviceWaitIdle0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkAllocateMemory0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkAllocateMemory0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkFreeMemory0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkFreeMemory0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkMapMemory0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JJI[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkMapMemory0
  (JNIEnv *, jclass, jobject, jobject, jlong, jlong, jint, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkUnmapMemory0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkUnmapMemory0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkFlushMappedMemoryRanges0
 * Signature: (Ljava/nio/ByteBuffer;I[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkFlushMappedMemoryRanges0
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkInvalidateMappedMemoryRanges0
 * Signature: (Ljava/nio/ByteBuffer;I[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkInvalidateMappedMemoryRanges0
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetDeviceMemoryCommitment0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetDeviceMemoryCommitment0
  (JNIEnv *, jclass, jobject, jobject, jlongArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkBindBufferMemory0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkBindBufferMemory0
  (JNIEnv *, jclass, jobject, jobject, jobject, jlong);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkBindImageMemory0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkBindImageMemory0
  (JNIEnv *, jclass, jobject, jobject, jobject, jlong);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetBufferMemoryRequirements0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetBufferMemoryRequirements0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetImageMemoryRequirements0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetImageMemoryRequirements0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetImageSparseMemoryRequirements0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I[Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetImageSparseMemoryRequirements0
  (JNIEnv *, jclass, jobject, jobject, jintArray, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceSparseImageFormatProperties0
 * Signature: (Ljava/nio/ByteBuffer;IIIII[I[Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceSparseImageFormatProperties0
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jintArray, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkQueueBindSparse0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkQueueBindSparse0
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateFence0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateFence0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyFence0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyFence0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkResetFences0
 * Signature: (Ljava/nio/ByteBuffer;I[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkResetFences0
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetFenceStatus0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkGetFenceStatus0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkWaitForFences0
 * Signature: (Ljava/nio/ByteBuffer;I[Ljava/nio/ByteBuffer;ZJ)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkWaitForFences0
  (JNIEnv *, jclass, jobject, jint, jobjectArray, jboolean, jlong);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateSemaphore0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateSemaphore0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroySemaphore0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroySemaphore0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateEvent0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateEvent0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyEvent0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyEvent0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetEventStatus0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkGetEventStatus0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkSetEvent0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkSetEvent0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkResetEvent0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkResetEvent0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateQueryPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateQueryPool0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyQueryPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyQueryPool0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetQueryPoolResults0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIJLjava/nio/Buffer;JI)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkGetQueryPoolResults0
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jlong, jobject, jlong, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateBuffer0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyBuffer0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateBufferView0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateBufferView0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyBufferView0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyBufferView0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateImage0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyImage0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetImageSubresourceLayout0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetImageSubresourceLayout0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateImageView0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateImageView0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyImageView0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyImageView0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateShaderModule0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateShaderModule0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyShaderModule0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyShaderModule0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreatePipelineCache0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreatePipelineCache0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyPipelineCache0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyPipelineCache0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPipelineCacheData0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[JLjava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkGetPipelineCacheData0
  (JNIEnv *, jclass, jobject, jobject, jlongArray, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkMergePipelineCaches0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkMergePipelineCaches0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateGraphicsPipelines0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateGraphicsPipelines0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateComputePipelines0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateComputePipelines0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyPipeline0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyPipeline0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreatePipelineLayout0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreatePipelineLayout0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyPipelineLayout0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyPipelineLayout0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateSampler0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateSampler0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroySampler0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroySampler0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateDescriptorSetLayout0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateDescriptorSetLayout0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyDescriptorSetLayout0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyDescriptorSetLayout0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateDescriptorPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateDescriptorPool0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyDescriptorPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyDescriptorPool0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkResetDescriptorPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkResetDescriptorPool0
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkAllocateDescriptorSets0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkAllocateDescriptorSets0
  (JNIEnv *, jclass, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkFreeDescriptorSets0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkFreeDescriptorSets0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkUpdateDescriptorSets0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkUpdateDescriptorSets0
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateFramebuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateFramebuffer0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyFramebuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyFramebuffer0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateRenderPass0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkCreateRenderPass0
  (JNIEnv *, jclass, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyRenderPass0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyRenderPass0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetRenderAreaGranularity0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetRenderAreaGranularity0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateCommandPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateCommandPool0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyCommandPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyCommandPool0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkResetCommandPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkResetCommandPool0
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkAllocateCommandBuffers0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkAllocateCommandBuffers0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkFreeCommandBuffers0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkFreeCommandBuffers0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkBeginCommandBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkBeginCommandBuffer0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEndCommandBuffer0
 * Signature: (Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkEndCommandBuffer0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkResetCommandBuffer0
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkResetCommandBuffer0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdBindPipeline0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdBindPipeline0
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetViewport0
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetViewport0
  (JNIEnv *, jclass, jobject, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetScissor0
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetScissor0
  (JNIEnv *, jclass, jobject, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetLineWidth0
 * Signature: (Ljava/nio/ByteBuffer;F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetLineWidth0
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetDepthBias0
 * Signature: (Ljava/nio/ByteBuffer;FFF)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetDepthBias0
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetBlendConstants0
 * Signature: (Ljava/nio/ByteBuffer;[F)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetBlendConstants0
  (JNIEnv *, jclass, jobject, jfloatArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetDepthBounds0
 * Signature: (Ljava/nio/ByteBuffer;FF)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetDepthBounds0
  (JNIEnv *, jclass, jobject, jfloat, jfloat);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetStencilCompareMask0
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetStencilCompareMask0
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetStencilWriteMask0
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetStencilWriteMask0
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetStencilReference0
 * Signature: (Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetStencilReference0
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdBindDescriptorSets0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdBindDescriptorSets0
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jobject, jint, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdBindIndexBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JI)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdBindIndexBuffer0
  (JNIEnv *, jclass, jobject, jobject, jlong, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdBindVertexBuffers0
 * Signature: (Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;[J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdBindVertexBuffers0
  (JNIEnv *, jclass, jobject, jint, jint, jobject, jlongArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdDraw0
 * Signature: (Ljava/nio/ByteBuffer;IIII)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdDraw0
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdDrawIndexed0
 * Signature: (Ljava/nio/ByteBuffer;IIIII)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdDrawIndexed0
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdDrawIndirect0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JII)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdDrawIndirect0
  (JNIEnv *, jclass, jobject, jobject, jlong, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdDrawIndexedIndirect0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JII)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdDrawIndexedIndirect0
  (JNIEnv *, jclass, jobject, jobject, jlong, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdDispatch0
 * Signature: (Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdDispatch0
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdDispatchIndirect0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdDispatchIndirect0
  (JNIEnv *, jclass, jobject, jobject, jlong);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdCopyBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdCopyBuffer0
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdCopyImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdCopyImage0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdBlitImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdBlitImage0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jint, jint, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdCopyBufferToImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdCopyBufferToImage0
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdCopyImageToBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdCopyImageToBuffer0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdUpdateBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JJ[I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdUpdateBuffer0
  (JNIEnv *, jclass, jobject, jobject, jlong, jlong, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdFillBuffer0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;JJI)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdFillBuffer0
  (JNIEnv *, jclass, jobject, jobject, jlong, jlong, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdClearColorImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdClearColorImage0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdClearDepthStencilImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdClearDepthStencilImage0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdClearAttachments0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdClearAttachments0
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdResolveImage0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdResolveImage0
  (JNIEnv *, jclass, jobject, jobject, jint, jobject, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdSetEvent0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdSetEvent0
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdResetEvent0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdResetEvent0
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdWaitEvents0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdWaitEvents0
  (JNIEnv *, jclass, jobject, jint, jobject, jint, jint, jint, jobject, jint, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdPipelineBarrier0
 * Signature: (Ljava/nio/ByteBuffer;IIIILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdPipelineBarrier0
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jobject, jint, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdBeginQuery0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdBeginQuery0
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdEndQuery0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdEndQuery0
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdResetQueryPool0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdResetQueryPool0
  (JNIEnv *, jclass, jobject, jobject, jint, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdWriteTimestamp0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdWriteTimestamp0
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdCopyQueryPoolResults0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IILjava/nio/ByteBuffer;JJI)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdCopyQueryPoolResults0
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jobject, jlong, jlong, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdPushConstants0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdPushConstants0
  (JNIEnv *, jclass, jobject, jobject, jint, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdBeginRenderPass0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdBeginRenderPass0
  (JNIEnv *, jclass, jobject, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdNextSubpass0
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdNextSubpass0
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdEndRenderPass0
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdEndRenderPass0
  (JNIEnv *, jclass, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCmdExecuteCommands0
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkCmdExecuteCommands0
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateAndroidSurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateAndroidSurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateMirSurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateMirSurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateWaylandSurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateWaylandSurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateWin32SurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateWin32SurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateXcbSurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateXcbSurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateXlibSurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateXlibSurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroySurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroySurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateDisplayPlaneSurfaceKHR0
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateDisplayPlaneSurfaceKHR0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class bor_vulkan_Vk10_PLATFORMS */

#ifndef _Included_bor_vulkan_Vk10_PLATFORMS
#define _Included_bor_vulkan_Vk10_PLATFORMS
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
