/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bor_vulkan_Vk10 */

#ifndef _Included_bor_vulkan_Vk10
#define _Included_bor_vulkan_Vk10
#ifdef __cplusplus
extern "C" {
#endif
#undef bor_vulkan_Vk10_VK_LOD_CLAMP_NONE
#define bor_vulkan_Vk10_VK_LOD_CLAMP_NONE 1000.0f
#undef bor_vulkan_Vk10_VK_REMAINING_MIP_LEVELS
#define bor_vulkan_Vk10_VK_REMAINING_MIP_LEVELS 2147483647L
#undef bor_vulkan_Vk10_VK_REMAINING_ARRAY_LAYERS
#define bor_vulkan_Vk10_VK_REMAINING_ARRAY_LAYERS 2147483647L
#undef bor_vulkan_Vk10_VK_WHOLE_SIZE
#define bor_vulkan_Vk10_VK_WHOLE_SIZE 9223372036854775807i64
#undef bor_vulkan_Vk10_VK_ATTACHMENT_UNUSED
#define bor_vulkan_Vk10_VK_ATTACHMENT_UNUSED 2147483647L
#undef bor_vulkan_Vk10_VK_TRUE
#define bor_vulkan_Vk10_VK_TRUE 1L
#undef bor_vulkan_Vk10_VK_FALSE
#define bor_vulkan_Vk10_VK_FALSE 0L
#undef bor_vulkan_Vk10_VK_QUEUE_FAMILY_IGNORED
#define bor_vulkan_Vk10_VK_QUEUE_FAMILY_IGNORED 2147483647L
#undef bor_vulkan_Vk10_VK_SUBPASS_EXTERNAL
#define bor_vulkan_Vk10_VK_SUBPASS_EXTERNAL 2147483647L
#undef bor_vulkan_Vk10_VK_MAX_PHYSICAL_DEVICE_NAME_SIZE
#define bor_vulkan_Vk10_VK_MAX_PHYSICAL_DEVICE_NAME_SIZE 256L
#undef bor_vulkan_Vk10_VK_UUID_SIZE
#define bor_vulkan_Vk10_VK_UUID_SIZE 16L
#undef bor_vulkan_Vk10_VK_MAX_MEMORY_TYPES
#define bor_vulkan_Vk10_VK_MAX_MEMORY_TYPES 32L
#undef bor_vulkan_Vk10_VK_MAX_MEMORY_HEAPS
#define bor_vulkan_Vk10_VK_MAX_MEMORY_HEAPS 16L
#undef bor_vulkan_Vk10_VK_MAX_EXTENSION_NAME_SIZE
#define bor_vulkan_Vk10_VK_MAX_EXTENSION_NAME_SIZE 256L
#undef bor_vulkan_Vk10_VK_MAX_DESCRIPTION_SIZE
#define bor_vulkan_Vk10_VK_MAX_DESCRIPTION_SIZE 256L
#undef bor_vulkan_Vk10_VK_KHR_surface
#define bor_vulkan_Vk10_VK_KHR_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_SURFACE_SPEC_VERSION 25L
#undef bor_vulkan_Vk10_VK_KHR_swapchain
#define bor_vulkan_Vk10_VK_KHR_swapchain 1L
#undef bor_vulkan_Vk10_VK_KHR_SWAPCHAIN_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_SWAPCHAIN_SPEC_VERSION 67L
#undef bor_vulkan_Vk10_VK_KHR_display
#define bor_vulkan_Vk10_VK_KHR_display 1L
#undef bor_vulkan_Vk10_VK_KHR_DISPLAY_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_DISPLAY_SPEC_VERSION 21L
#undef bor_vulkan_Vk10_VK_KHR_display_swapchain
#define bor_vulkan_Vk10_VK_KHR_display_swapchain 1L
#undef bor_vulkan_Vk10_VK_KHR_DISPLAY_SWAPCHAIN_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_DISPLAY_SWAPCHAIN_SPEC_VERSION 9L
#undef bor_vulkan_Vk10_VK_KHR_xlib_surface
#define bor_vulkan_Vk10_VK_KHR_xlib_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_XLIB_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_XLIB_SURFACE_SPEC_VERSION 6L
#undef bor_vulkan_Vk10_VK_KHR_xcb_surface
#define bor_vulkan_Vk10_VK_KHR_xcb_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_XCB_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_XCB_SURFACE_SPEC_VERSION 6L
#undef bor_vulkan_Vk10_VK_KHR_wayland_surface
#define bor_vulkan_Vk10_VK_KHR_wayland_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_WAYLAND_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_WAYLAND_SURFACE_SPEC_VERSION 5L
#undef bor_vulkan_Vk10_VK_KHR_mir_surface
#define bor_vulkan_Vk10_VK_KHR_mir_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_MIR_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_MIR_SURFACE_SPEC_VERSION 4L
#undef bor_vulkan_Vk10_VK_KHR_android_surface
#define bor_vulkan_Vk10_VK_KHR_android_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_ANDROID_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_ANDROID_SURFACE_SPEC_VERSION 6L
#undef bor_vulkan_Vk10_VK_KHR_win32_surface
#define bor_vulkan_Vk10_VK_KHR_win32_surface 1L
#undef bor_vulkan_Vk10_VK_KHR_WIN32_SURFACE_SPEC_VERSION
#define bor_vulkan_Vk10_VK_KHR_WIN32_SURFACE_SPEC_VERSION 5L
#undef bor_vulkan_Vk10_VK_EXT_debug_report
#define bor_vulkan_Vk10_VK_EXT_debug_report 1L
#undef bor_vulkan_Vk10_VK_EXT_DEBUG_REPORT_SPEC_VERSION
#define bor_vulkan_Vk10_VK_EXT_DEBUG_REPORT_SPEC_VERSION 2L
#undef bor_vulkan_Vk10_VK_NV_glsl_shader
#define bor_vulkan_Vk10_VK_NV_glsl_shader 1L
#undef bor_vulkan_Vk10_VK_NV_GLSL_SHADER_SPEC_VERSION
#define bor_vulkan_Vk10_VK_NV_GLSL_SHADER_SPEC_VERSION 1L
/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateInstance0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateInstance0
  (JNIEnv *, jclass, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyInstance0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyInstance0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumeratePhysicalDevices0
 * Signature: (Ljava/nio/Buffer;[I[Ljava/nio/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkEnumeratePhysicalDevices0
  (JNIEnv *, jclass, jobject, jintArray, jobjectArray, jint);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceFeatures0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceFeatures0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceFormatProperties0
 * Signature: (Ljava/nio/Buffer;ILjava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceFormatProperties0
  (JNIEnv *, jclass, jobject, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceImageFormatProperties0
 * Signature: (Ljava/nio/Buffer;IIIIILjava/nio/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceImageFormatProperties0
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceProperties0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceProperties0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceQueueFamilyProperties0
 * Signature: (Ljava/nio/Buffer;[I)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceQueueFamilyProperties0
  (JNIEnv *, jclass, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetPhysicalDeviceMemoryProperties0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkGetPhysicalDeviceMemoryProperties0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetInstanceProcAddr0
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkGetInstanceProcAddr0
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetDeviceProcAddr0
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkGetDeviceProcAddr0
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkCreateDevice0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;Ljava/nio/Buffer;[I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkCreateDevice0
  (JNIEnv *, jclass, jobject, jobject, jobject, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkDestroyDevice0
 * Signature: (Ljava/nio/Buffer;Ljava/nio/Buffer;)V
 */
JNIEXPORT void JNICALL Java_bor_vulkan_Vk10_vkDestroyDevice0
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateInstanceExtensionProperties0
 * Signature: (Ljava/lang/String;[I[I)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_bor_vulkan_Vk10_vkEnumerateInstanceExtensionProperties0
  (JNIEnv *, jclass, jstring, jintArray, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateDeviceExtensionProperties0
 * Signature: (Ljava/nio/Buffer;Ljava/lang/String;[I[I)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_bor_vulkan_Vk10_vkEnumerateDeviceExtensionProperties0
  (JNIEnv *, jclass, jobject, jstring, jintArray, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateInstanceLayerProperties0
 * Signature: ([I[I)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_bor_vulkan_Vk10_vkEnumerateInstanceLayerProperties0
  (JNIEnv *, jclass, jintArray, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkEnumerateDeviceLayerProperties0
 * Signature: (Ljava/nio/Buffer;[I[I)[Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobjectArray JNICALL Java_bor_vulkan_Vk10_vkEnumerateDeviceLayerProperties0
  (JNIEnv *, jclass, jobject, jintArray, jintArray);

/*
 * Class:     bor_vulkan_Vk10
 * Method:    vkGetDeviceQueue0
 * Signature: (Ljava/nio/Buffer;II)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_bor_vulkan_Vk10_vkGetDeviceQueue0
  (JNIEnv *, jclass, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
